import { ReactNode } from 'react';
import './globals.css'
import Link from 'next/link';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

type LayoutPropiedades = {
  children: ReactNode;
};

export default function RootLayout({ children }: LayoutPropiedades) {
  return (
    <html lang="es">
      <body className="flex min-h-screen">
        <aside className="w-70 bg-gray-400 text-black p-2">
          <nav className="flex flex-col space-y-4">
            <Link href="/" className="hover:text-amber-50">Inicio</Link>
            <Link href="/login" className="hover:text-amber-50">Login</Link>
            <Link href="/ver_inventario" className="hover:text-amber-50">Inventario</Link>
            <Link href="/administrar_inv" className="hover:text-amber-50">Administrar Inv.</Link>
            <Link href="/alertas" className="hover:text-amber-50">Alertas</Link>
            <Link href="/AI" className="hover:text-amber-50">AI</Link>
          </nav>
        </aside>
        <main className="flex-1 p-8 bg-gray-300">{children}</main>
      </body>
    </html>
  );
}
